## Cost Function Minimization using Matrix

In [1]:
import numpy as np

Assume Values for Features and make the output function.

In [2]:
x0 = np.array([i**3 for i in range(10)])
x1 = np.array([i**2 for i in range(3,13)])
x2 = np.array([i for i in range(1,21,2)])
x3 = np.array([i for i in range(31,61,3)])

y = x0 + x1*6 + x2*4 + x3*2

print(x0)
print(x1)
print(x2)
print(x3)
print(y)


[  0   1   8  27  64 125 216 343 512 729]
[  9  16  25  36  49  64  81 100 121 144]
[ 1  3  5  7  9 11 13 15 17 19]
[31 34 37 40 43 46 49 52 55 58]
[ 120  177  252  351  480  645  852 1107 1416 1785]


Stack all feature columnwise to make feature matrics.

In [3]:
x = np.column_stack((x0,x1,x2,x3))
x

array([[  0,   9,   1,  31],
       [  1,  16,   3,  34],
       [  8,  25,   5,  37],
       [ 27,  36,   7,  40],
       [ 64,  49,   9,  43],
       [125,  64,  11,  46],
       [216,  81,  13,  49],
       [343, 100,  15,  52],
       [512, 121,  17,  55],
       [729, 144,  19,  58]])

Find the optimum value of Theta Array.
theta = (X^T\*X)^-1 * (X^T\*Y)

In [4]:
theta = np.dot(np.linalg.inv(np.dot(x.transpose(),x)),np.dot(x.transpose(),y))

Predict Y from Optimized theta values. Y = theta * X^T

In [5]:
pred_y = np.dot(theta.reshape(1,-1), x.transpose())

In [6]:
print(pred_y)
print(y)

[[ 120.  177.  252.  351.  480.  645.  852. 1107. 1416. 1785.]]
[ 120  177  252  351  480  645  852 1107 1416 1785]
